leaFunction =  compile preprocessFileLineNumbers "lea\loadout-init.sqf"; call leaFunction;//line generated by LEA.

call compile preprocessFileLineNumbers "a3\guard.sqf";
call compile preprocessFileLineNumbers "a3\tasks.sqf";

enableEngineArtillery false;

// Task Force Radio Client Settings
tf_no_auto_long_range_radio = true;
tf_give_personal_radio_to_regular_soldier = false;
tf_give_microdagr_to_soldier = false;
tf_same_sw_frequencies_for_side = true;
tf_same_lr_frequencies_for_side = true;
tf_same_dd_frequencies_for_side = false;

// Nema snimanja
enableSaving [ false, false ];

// Ušutkaj AI 
enableSentences false;

// custom mission setup

if (isServer) then {
	grpWest1 = createGroup west;
	discoverInsurgents = {
		{
			if (side _x == independent) then {
				[_x] joinSilent grpNull;
				[_x] joinSilent grpWest1;
			};
		} forEach allUnits;
	};
};

waitUntil {player==player};

taskFindWeapons = [player,"taskFindWeapons","Steal weapons","Break into guarded warehouse and steal weapons and ammo",getMarkerPos "warehouse"] call a3_createTask;
taskEscape = [player,"taskEscape","Escape to Pusta","After stealing weapons, escape to safe house in Pusta",getMarkerPos "safeHouse"] call a3_createTask;

if (!isDedicated) then {
	[] spawn {
		private ["_isArmed"];
		_isArmed = false;

		waitUntil {sleep 1; !isNil "introFinished"};
		[player,10,grpWest1] spawn a3_monitorGuards;
		
		while {!_isArmed or isNil "grpWest1"} do {
			sleep 1;
			
			_isArmed = [player] call a3_isArmed;
			
			if (_isArmed) then {
				// player joins blufor
				[player] joinSilent grpNull;
				[player] joinSilent grpWest1;				
			};
		};
	};	
}