leaFunction =  compile preprocessFileLineNumbers "lea\loadout-init.sqf"; call leaFunction;//line generated by LEA.

enableEngineArtillery false;

// Task Force Radio Client Settings
tf_no_auto_long_range_radio = true;
tf_give_personal_radio_to_regular_soldier = false;
tf_give_microdagr_to_soldier = false;
tf_same_sw_frequencies_for_side = true;
tf_same_lr_frequencies_for_side = true;
tf_same_dd_frequencies_for_side = false;

// Nema snimanja
enableSaving [ false, false ];

// Ušutkaj AI 
enableSentences false;

if (!isDedicated) then {
	waitUntil{player==player};
	_devMode="Dev" call BIS_fnc_getParamValue;
	
	if (_devMode==1) then {
		hint "Development mode enabled, player is indestructible.";
		player allowDamage false;
	};
};