leaFunction =  compile preprocessFileLineNumbers "lea\loadout-init.sqf"; call leaFunction;//line generated by LEA.

enableEngineArtillery false;

// Task Force Radio Client Settings
tf_no_auto_long_range_radio = true;
tf_give_personal_radio_to_regular_soldier = false;
tf_give_microdagr_to_soldier = false;
tf_same_sw_frequencies_for_side = true;
tf_same_lr_frequencies_for_side = true;
tf_same_dd_frequencies_for_side = false;

// Nema snimanja
enableSaving [ false, false ];

// Ušutkaj AI 
enableSentences false;

// Dev mode
if (!isDedicated) then {
	waitUntil{player==player};
	_devMode="Dev" call BIS_fnc_getParamValue;
	//uncomment this for preview dev mode
	//_devMode=1;
	
	if (_devMode==1) then {
		hint "Development mode enabled, player is indestructible.";
		player allowDamage false;
		
		player addAction [
			"Teleport",
			{ 
				openMap true; 
				(_this select 1) onMapSingleClick 
				{ 
					_this setPos _pos; 					
					onMapSingleClick {false};
					openMap false;
					cutText ["Teleported!","PLAIN",2];
				};				
			},
			nil,
			1,
			false
		];	

		player addAction [
			"Reveal all",
			{
				{
					(group player) reveal [_x,4];
					_veh=vehicle _x;
					
					if (!isNil "_veh") then {
						(group player) reveal [_veh,4];
					};
				} forEach allUnits;
				
				cutText ["All revealed!","PLAIN",2];
			},
			nil,
			1,
			false		
		];
	};
};

// briefing
player createDiaryRecord ["Diary",["Supports","During our time in Pusta, we've made a few friends with the local hunters and they've expressed their discontent with the current regime. We've assigned them an east-bound vector from Pusta with orders to kill anything Russian. They may prove a valuable asset...if they survive."]];

player createDiaryRecord ["Diary",["Execution","There is no need to kill the civilians as they are unarmed and non-hostile. You may, however, if you choose to do so. Just remember - our goal is to gain the local populace trust and killing their family might not be the best way to go about doing that."]];

player createDiaryRecord ["Diary",["Mission","Every friday night a group of collaborators from the power plant gathers at the brothel near the Topolka Dam. They drink until late at night then have their way with the women. Your mission is to assault them and take away all items which may contain intel.<br></br><br></br>Amongst them there is a Chinese expert sent to help with the powerplant routines. We want to send a message to any outsider who thinks such behaviour can go unpunished. Kill him."]];

player createDiaryRecord ["Diary",["Situation","Our activities at Elektrozavodsk have drawn attention from the enemy. There are patrolling soldiers all around the objective.<br></br><br></br>You can approach the target from west, north or east, but DO NOT attempt a southern approach. The area is littered with enemy soldiers and anti-personel mines."]];
