/**
* Generated by LEA for Arma 3
* Version: 2.0.22
* Thu Feb 05 20:56:37 CET 2015
* Mission file name: Nail_Clippers.Altis
* Mission name: Nail_Clippers.Altis
* Required mods:
* + ArmA 3
* 
* Call the script: _dummy = [] execvm "lea\loadoutMultiplayer.sqf";
* 
*/

/**
* Loadout for crates
*/

  clearweaponcargoGlobal weaponcrate;
  clearmagazinecargoGlobal weaponcrate;
  clearitemcargoGlobal weaponcrate;

  weaponcrate addmagazinecargoGlobal ["RH_30Rnd_556x45_Mk262",4];
  weaponcrate addmagazinecargoGlobal ["1Rnd_HE_Grenade_shell",5];
  weaponcrate addmagazinecargoGlobal ["7Rnd_408_Mag",5];
  weaponcrate addmagazinecargoGlobal ["smokeshell",10];
  weaponcrate addmagazinecargoGlobal ["handgrenade",10];
  weaponcrate additemcargoGlobal ["cse_bandage_basic",20];
  weaponcrate additemcargoGlobal ["cse_quikclot",20];
  weaponcrate additemcargoGlobal ["cse_blood_iv_500",6];
  weaponcrate additemcargoGlobal ["cse_epinephrine",6];
  weaponcrate additemcargoGlobal ["cse_tourniquet",6];
  weaponcrate additemcargoGlobal ["cse_packing_bandage",6];
  weaponcrate additemcargoGlobal ["cse_morphine",10];
  weaponcrate additemcargoGlobal ["cse_blood_iv",10];
  weaponcrate additemcargoGlobal ["cse_saline_iv_500",12];
  weaponcrate addmagazinecargoGlobal ["APERSBoundingMine_Range_Mag",10];


  clearweaponcargoGlobal launchercrate;
  clearmagazinecargoGlobal launchercrate;
  clearitemcargoGlobal launchercrate;

  launchercrate addweaponcargoGlobal ["rhs_weap_rpg7",5];
  launchercrate addweaponcargoGlobal ["rhs_weap_rpg26",5];
  launchercrate addweaponcargoGlobal ["rhs_weap_igla",3];
  launchercrate addmagazinecargoGlobal ["rhs_rpg26_mag",5];
  launchercrate addmagazinecargoGlobal ["rhs_rpg7_PG7VL_mag",5];
  launchercrate addmagazinecargoGlobal ["rhs_rpg7_PG7VR_mag",5];
  launchercrate addmagazinecargoGlobal ["rhs_rpg7_OG7V_mag",5];
  launchercrate addmagazinecargoGlobal ["rhs_rpg7_TBG7V_mag",5];
  launchercrate addmagazinecargoGlobal ["rhs_mag_9k38_rocket",9];
  launchercrate additemcargoGlobal ["rhs_acc_1pn93_1",5];
  launchercrate additemcargoGlobal ["rhs_acc_pgo7v",5];
  
  clearweaponcargoGlobal explosivecrate;
  clearmagazinecargoGlobal explosivecrate;
  clearitemcargoGlobal explosivecrate;

  explosivecrate addmagazinecargoGlobal ["rhs_mine_tm62m_mag",4];
  explosivecrate addmagazinecargoGlobal ["rhs_mine_M19_mag",4];
  explosivecrate addmagazinecargoGlobal ["rhs_mine_pmn2_mag",8];
  explosivecrate addmagazinecargoGlobal ["rhs_mag_rgd5",10];
  explosivecrate addmagazinecargoGlobal ["rhs_mag_zarya2",10];
  explosivecrate addmagazinecargoGlobal ["rhs_mag_plamyam",10];
  explosivecrate addmagazinecargoGlobal ["DemoCharge_Remote_Mag",10];
  explosivecrate addmagazinecargoGlobal ["ATMine_Range_Mag",4];
  explosivecrate addmagazinecargoGlobal ["SLAMDirectionalMine_Wire_Mag",4];
  explosivecrate addmagazinecargoGlobal ["SatchelCharge_Remote_Mag",4];

  clearweaponcargoGlobal weaponcrate_1;
  clearmagazinecargoGlobal weaponcrate_1;
  clearitemcargoGlobal weaponcrate_1;

  weaponcrate_1 addweaponcargoGlobal ["rhs_weap_ak74m_folded",5];
  weaponcrate_1 addweaponcargoGlobal ["rhs_weap_ak74m",5];
  weaponcrate_1 addmagazinecargoGlobal ["rhs_30Rnd_545x39_7N10_AK",30];
  weaponcrate_1 addmagazinecargoGlobal ["rhs_30Rnd_545x39_AK",30];
  weaponcrate_1 additemcargoGlobal ["rhs_acc_1p29",10];
  weaponcrate_1 additemcargoGlobal ["rhs_acc_1p63",10];
  weaponcrate_1 additemcargoGlobal ["rhs_acc_tgpa",10];
  weaponcrate_1 addBackpackCargoGlobal ["rhs_assault_umbts",10];
  
  clearweaponcargoGlobal launchercrate_1;
  clearmagazinecargoGlobal launchercrate_1;
  clearitemcargoGlobal launchercrate_1;

  launchercrate_1 addweaponcargoGlobal ["rhs_weap_rpg7",5];
  launchercrate_1 addweaponcargoGlobal ["rhs_weap_rpg26",5];
  launchercrate_1 addweaponcargoGlobal ["rhs_weap_igla",3];
  launchercrate_1 addmagazinecargoGlobal ["rhs_rpg26_mag",5];
  launchercrate_1 addmagazinecargoGlobal ["rhs_rpg7_PG7VL_mag",5];
  launchercrate_1 addmagazinecargoGlobal ["rhs_rpg7_PG7VR_mag",5];
  launchercrate_1 addmagazinecargoGlobal ["rhs_rpg7_OG7V_mag",5];
  launchercrate_1 addmagazinecargoGlobal ["rhs_rpg7_TBG7V_mag",5];
  launchercrate_1 addmagazinecargoGlobal ["rhs_mag_9k38_rocket",9];
  launchercrate_1 additemcargoGlobal ["rhs_acc_1pn93_1",5];
  launchercrate additemcargoGlobal ["rhs_acc_pgo7v",5];

  clearweaponcargoGlobal explosivecrate_1;
  clearmagazinecargoGlobal explosivecrate_1;
  clearitemcargoGlobal explosivecrate_1;

  explosivecrate_1 addmagazinecargoGlobal ["rhs_mine_tm62m_mag",4];
  explosivecrate_1 addmagazinecargoGlobal ["rhs_mine_M19_mag",4];
  explosivecrate_1 addmagazinecargoGlobal ["rhs_mine_pmn2_mag",8];
  explosivecrate_1 addmagazinecargoGlobal ["rhs_mag_rgd5",10];
  explosivecrate_1 addmagazinecargoGlobal ["rhs_mag_zarya2",10];
  explosivecrate_1 addmagazinecargoGlobal ["rhs_mag_plamyam",10];
  explosivecrate_1 addmagazinecargoGlobal ["DemoCharge_Remote_Mag",10];
  explosivecrate_1 addmagazinecargoGlobal ["ATMine_Range_Mag",4];
  explosivecrate_1 addmagazinecargoGlobal ["SLAMDirectionalMine_Wire_Mag",4];
  explosivecrate_1 addmagazinecargoGlobal ["SatchelCharge_Remote_Mag",4];

  
/**
* Loadout for soldiers units
*/

if (!isNil "teamleader") then {
	if (player == teamleader) exitwith {
removeallweapons teamleader;
removeallassigneditems teamleader;
removeBackpack teamleader;
removeVest teamleader;
removeHeadgear teamleader;
removeUniform teamleader;
removeGoggles teamleader;

teamleader addWeapon "ItemMap";
teamleader addWeapon "ItemWatch";
teamleader addWeapon "ItemCompass";
teamleader addWeapon "ItemGPS";
teamleader addWeapon "H_HelmetB_desert";
teamleader addWeapon "G_Tactical_Clear";
teamleader addWeapon "NVGoggles";
teamleader addWeapon "Rangefinder";
teamleader addBackpack "B_Carryall_khk";
(backpackContainer teamleader) addmagazinecargoGlobal ["RH_30Rnd_556x45_Mk262",1];
(backpackContainer teamleader) addmagazinecargoGlobal ["1Rnd_HE_Grenade_shell",1];
teamleader addWeapon "RH_m4a1_ris_m203_tg";
removeBackpack teamleader;
teamleader addPrimaryWeaponItem "RH_Saker_tg";
teamleader addPrimaryWeaponItem "optic_HAMR";
teamleader addPrimaryWeaponItem "RH_peq15";
teamleader addBackpack "B_Carryall_khk";
(backpackContainer teamleader) addmagazinecargoGlobal ["11Rnd_45ACP_Mag",1];
teamleader addWeapon "hgun_Pistol_heavy_01_MRD_F";
teamleader addHandgunItem "muzzle_snds_acp";
removeBackpack teamleader;
teamleader addBackpack "B_Carryall_khk";
clearItemCargoGlobal (backpackContainer teamleader);
clearMagazineCargoGlobal (backpackContainer teamleader);
clearWeaponCargoGlobal (backpackContainer teamleader);
(backpackContainer teamleader) addmagazinecargoGlobal ["RH_30Rnd_556x45_Mk262",1];
(backpackContainer teamleader) addmagazinecargoGlobal ["1Rnd_HE_Grenade_shell",5];
(backpackContainer teamleader) addmagazinecargoGlobal ["smokeshell",3];
(backpackContainer teamleader) addmagazinecargoGlobal ["handgrenade",3];
(backpackContainer teamleader) addmagazinecargoGlobal ["APERSBoundingMine_Range_Mag",3];
(backpackContainer teamleader) additemcargoGlobal ["cse_bandage_basic",5];
(backpackContainer teamleader) additemcargoGlobal ["cse_packing_bandage",3];
(backpackContainer teamleader) additemcargoGlobal ["cse_morphine",2];
(backpackContainer teamleader) additemcargoGlobal ["cse_quikclot",4];
teamleader addVest "V_TacVest_brn";
clearItemCargoGlobal (vestContainer teamleader);
clearMagazineCargoGlobal (vestContainer teamleader);
clearWeaponCargoGlobal (vestContainer teamleader);
(vestContainer teamleader) addmagazinecargoGlobal ["RH_30Rnd_556x45_Mk262",5];
(vestContainer teamleader) addmagazinecargoGlobal ["1Rnd_HE_Grenade_shell",5];
teamleader forceAddUniform "U_B_GhillieSuit";
clearItemCargoGlobal (uniformContainer teamleader);
clearMagazineCargoGlobal (uniformContainer teamleader);
clearWeaponCargoGlobal (uniformContainer teamleader);
(uniformContainer teamleader) addmagazinecargoGlobal ["RH_30Rnd_556x45_Mk262",1];
(uniformContainer teamleader) addmagazinecargoGlobal ["11Rnd_45ACP_Mag",1];
teamleader addWeapon "ItemRadio";
teamleader selectWeapon (primaryWeapon teamleader);
	};
};

if (!isNil "sniper") then {
	if (player == sniper) exitwith {
removeallweapons sniper;
removeallassigneditems sniper;
removeBackpack sniper;
removeVest sniper;
removeHeadgear sniper;
removeUniform sniper;
removeGoggles sniper;
sniper addWeapon "ItemMap";
sniper addWeapon "ItemWatch";
sniper addWeapon "ItemCompass";
sniper addWeapon "ItemGPS";
sniper addWeapon "G_Tactical_Clear";
sniper addWeapon "NVGoggles";
sniper addWeapon "H_Booniehat_dirty";
sniper addWeapon "Laserdesignator";
sniper addBackpack "B_Carryall_khk";
(backpackContainer sniper) addmagazinecargoGlobal ["7Rnd_408_Mag",1];
sniper addWeapon "srifle_LRR_camo_F";
removeBackpack sniper;
sniper addPrimaryWeaponItem "optic_LRPS";
sniper addBackpack "B_Carryall_khk";
(backpackContainer sniper) addmagazinecargoGlobal ["11Rnd_45ACP_Mag",1];
sniper addWeapon "hgun_Pistol_heavy_01_MRD_F";
sniper addHandgunItem "muzzle_snds_acp";
removeBackpack sniper;
sniper addBackpack "B_Carryall_khk";
clearItemCargoGlobal (backpackContainer sniper);
clearMagazineCargoGlobal (backpackContainer sniper);
clearWeaponCargoGlobal (backpackContainer sniper);
(backpackContainer sniper) addmagazinecargoGlobal ["7Rnd_408_Mag",12];
(backpackContainer sniper) additemcargoGlobal ["cse_ab_Kestrel4500",1];
(backpackContainer sniper) additemcargoGlobal ["cse_ab_ATragMX",1];
(backpackContainer sniper) additemcargoGlobal ["Laserbatteries",1];

(backpackContainer sniper) additemcargoGlobal ["cse_bandage_basic",5];
(backpackContainer sniper) additemcargoGlobal ["cse_packing_bandage",3];
(backpackContainer sniper) additemcargoGlobal ["cse_morphine",2];
(backpackContainer sniper) additemcargoGlobal ["cse_quikclot",4];

sniper addVest "V_TacVest_brn";
clearItemCargoGlobal (vestContainer sniper);
clearMagazineCargoGlobal (vestContainer sniper);
clearWeaponCargoGlobal (vestContainer sniper);
(vestContainer sniper) addmagazinecargoGlobal ["smokeshell",5];
(vestContainer sniper) addmagazinecargoGlobal ["handgrenade",3];
sniper forceAddUniform "U_B_GhillieSuit";
clearItemCargoGlobal (uniformContainer sniper);
clearMagazineCargoGlobal (uniformContainer sniper);
clearWeaponCargoGlobal (uniformContainer sniper);
(uniformContainer sniper) addmagazinecargoGlobal ["11Rnd_45ACP_Mag",1];
sniper addWeapon "ItemRadio";
sniper selectWeapon (primaryWeapon sniper);
	};
};

if (!isNil "cls") then {
	if (player == cls) exitwith {
removeallweapons cls;
removeallassigneditems cls;
removeBackpack cls;
removeVest cls;
removeHeadgear cls;
removeUniform cls;
removeGoggles cls;

cls addWeapon "ItemMap";
cls addWeapon "ItemWatch";
cls addWeapon "ItemCompass";
cls addWeapon "ItemGPS";
cls addWeapon "G_Tactical_Clear";
cls addWeapon "NVGoggles";
cls addWeapon "H_HelmetB_desert";
cls addBackpack "B_AssaultPack_rgr_ReconMedic";
(backpackContainer cls) addmagazinecargoGlobal ["RH_30Rnd_556x45_Mk262",1];
cls addWeapon "RH_m4a1_ris_tg";
removeBackpack cls;
cls addPrimaryWeaponItem "RH_saker_tg";
cls addPrimaryWeaponItem "optic_HAMR";
cls addPrimaryWeaponItem "RH_peq15";
cls addBackpack "B_AssaultPack_rgr_ReconMedic";
(backpackContainer cls) addmagazinecargoGlobal ["11Rnd_45ACP_Mag",1];
(backpackContainer cls) additemcargoGlobal ["Medikit",1];
cls addWeapon "hgun_Pistol_heavy_01_MRD_F";
cls addHandgunItem "muzzle_snds_acp";
removeBackpack cls;
cls addBackpack "B_AssaultPack_rgr_ReconMedic";
clearItemCargoGlobal (backpackContainer cls);
clearMagazineCargoGlobal (backpackContainer cls);
clearWeaponCargoGlobal (backpackContainer cls);
(backpackContainer cls) addmagazinecargoGlobal ["RH_30Rnd_556x45_Mk262",3];
(backpackContainer cls) additemcargoGlobal ["cse_bandage_basic",10];
(backpackContainer cls) additemcargoGlobal ["cse_blood_iv",10];
(backpackContainer cls) additemcargoGlobal ["cse_saline_iv_500",12];
(backpackContainer cls) additemcargoGlobal ["cse_epinephrine",12];
(backpackContainer cls) additemcargoGlobal ["cse_packing_bandage",10];
(backpackContainer cls) additemcargoGlobal ["cse_morphine",10];
(backpackContainer cls) additemcargoGlobal ["cse_quikclot",15];
cls addVest "V_TacVest_brn";
clearItemCargoGlobal (vestContainer cls);
clearMagazineCargoGlobal (vestContainer cls);
clearWeaponCargoGlobal (vestContainer cls);
(vestContainer cls) addmagazinecargoGlobal ["RH_30Rnd_556x45_Mk262",1];
(vestContainer cls) addmagazinecargoGlobal ["smokeshell",5];
(vestContainer cls) addmagazinecargoGlobal ["handgrenade",3];
cls forceAddUniform "U_B_GhillieSuit";
clearItemCargoGlobal (uniformContainer cls);
clearMagazineCargoGlobal (uniformContainer cls);
clearWeaponCargoGlobal (uniformContainer cls);
(uniformContainer cls) addmagazinecargoGlobal ["RH_30Rnd_556x45_Mk262",1];
(uniformContainer cls) addmagazinecargoGlobal ["11Rnd_45ACP_Mag",1];
cls addWeapon "ItemRadio";
cls selectWeapon (primaryWeapon cls);
	};
};


if (!isNil "spotter") then {
	if (player == spotter) exitwith {
removeallweapons spotter;
removeallassigneditems spotter;
removeBackpack spotter;
removeVest spotter;
removeHeadgear spotter;
removeUniform spotter;
removeGoggles spotter;

spotter addWeapon "ItemMap";
spotter addWeapon "ItemWatch";
spotter addWeapon "ItemCompass";
spotter addWeapon "ItemGPS";
spotter addWeapon "H_HelmetB_desert";
spotter addWeapon "G_Tactical_Clear";
spotter addWeapon "NVGoggles";
spotter addWeapon "Laserdesignator";
spotter addBackpack "B_Carryall_khk";
(backpackContainer spotter) addmagazinecargoGlobal ["20Rnd_762x51_Mag",1];
spotter addWeapon "srifle_EBR_F";
removeBackpack spotter;
spotter addPrimaryWeaponItem "RH_saker_tg";
spotter addPrimaryWeaponItem "optic_DMS";
spotter addPrimaryWeaponItem "muzzle_snds_B";
spotter addPrimaryWeaponItem "RH_peq15";
spotter addBackpack "B_Carryall_khk";
(backpackContainer spotter) addmagazinecargoGlobal ["11Rnd_45ACP_Mag",1];
spotter addWeapon "hgun_Pistol_heavy_01_MRD_F";
spotter addHandgunItem "muzzle_snds_acp";
removeBackpack spotter;
spotter addBackpack "B_Carryall_khk";
clearItemCargoGlobal (backpackContainer spotter);
clearMagazineCargoGlobal (backpackContainer spotter);
clearWeaponCargoGlobal (backpackContainer spotter);
(backpackContainer spotter) addmagazinecargoGlobal ["20Rnd_762x51_Mag",7];
(backpackContainer spotter) additemcargoGlobal ["cse_ab_Kestrel4500",1];
(backpackContainer spotter) additemcargoGlobal ["cse_ab_ATragMX",1];
(backpackContainer spotter) addmagazinecargoGlobal ["APERSBoundingMine_Range_Mag",4];
(backpackContainer spotter) additemcargoGlobal ["Laserbatteries",1];
(backpackContainer spotter) additemcargoGlobal ["cse_bandage_basic",5];
(backpackContainer spotter) additemcargoGlobal ["cse_packing_bandage",3];
(backpackContainer spotter) additemcargoGlobal ["cse_morphine",2];
(backpackContainer spotter) additemcargoGlobal ["cse_quikclot",4];
spotter addVest "V_TacVest_brn";
clearItemCargoGlobal (vestContainer spotter);
clearMagazineCargoGlobal (vestContainer spotter);
clearWeaponCargoGlobal (vestContainer spotter);
(vestContainer spotter) addmagazinecargoGlobal ["20Rnd_762x51_Mag",1];
(vestContainer spotter) addmagazinecargoGlobal ["smokeshell",5];
(vestContainer spotter) addmagazinecargoGlobal ["handgrenade",3];
spotter forceAddUniform "U_B_GhillieSuit";
clearItemCargoGlobal (uniformContainer spotter);
clearMagazineCargoGlobal (uniformContainer spotter);
clearWeaponCargoGlobal (uniformContainer spotter);
(uniformContainer spotter) addmagazinecargoGlobal ["11Rnd_45ACP_Mag",1];
spotter addWeapon "ItemRadio";
spotter selectWeapon (primaryWeapon spotter);
	};
};

if (!isNil "rifleman_1") then {
	if (player == rifleman_1) exitwith {
removeallweapons rifleman_1;
removeallassigneditems rifleman_1;
removeBackpack rifleman_1;
removeVest rifleman_1;
removeHeadgear rifleman_1;
removeUniform rifleman_1;
removeGoggles rifleman_1;

rifleman_1 addWeapon "ItemMap";
rifleman_1 addWeapon "ItemWatch";
rifleman_1 addWeapon "ItemCompass";
rifleman_1 addWeapon "ItemGPS";
rifleman_1  addWeapon "G_Tactical_Clear";
rifleman_1 addWeapon "NVGoggles";
rifleman_1 addWeapon "H_HelmetB_desert";
rifleman_1 addBackpack "B_Carryall_khk";
(backpackContainer rifleman_1) addmagazinecargoGlobal ["RH_30Rnd_556x45_Mk262",1];
rifleman_1 addWeapon "RH_m4a1_ris_tg";
removeBackpack rifleman_1;
rifleman_1 addPrimaryWeaponItem "RH_saker_tg";
rifleman_1 addPrimaryWeaponItem "optic_HAMR";
rifleman_1 addPrimaryWeaponItem "RH_peq15";
rifleman_1 addBackpack "B_Carryall_khk";
(backpackContainer rifleman_1) addmagazinecargoGlobal ["11Rnd_45ACP_Mag",1];
rifleman_1 addWeapon "hgun_Pistol_heavy_01_MRD_F";
rifleman_1 addHandgunItem "muzzle_snds_acp";
removeBackpack rifleman_1;
rifleman_1 addBackpack "B_Carryall_khk";
clearItemCargoGlobal (backpackContainer rifleman_1);
clearMagazineCargoGlobal (backpackContainer rifleman_1);
clearWeaponCargoGlobal (backpackContainer rifleman_1);
(backpackContainer rifleman_1) addmagazinecargoGlobal ["RH_30Rnd_556x45_Mk262",1];
(backpackContainer rifleman_1) addmagazinecargoGlobal ["APERSBoundingMine_Range_Mag",3];
(backpackContainer rifleman_1) additemcargoGlobal ["cse_bandage_basic",5];
(backpackContainer rifleman_1) additemcargoGlobal ["cse_packing_bandage",3];
(backpackContainer rifleman_1) additemcargoGlobal ["cse_morphine",2];
(backpackContainer rifleman_1) additemcargoGlobal ["cse_quikclot",4];
rifleman_1 addVest "V_TacVest_brn";
clearItemCargoGlobal (vestContainer rifleman_1);
clearMagazineCargoGlobal (vestContainer rifleman_1);
clearWeaponCargoGlobal (vestContainer rifleman_1);
(vestContainer rifleman_1) addmagazinecargoGlobal ["RH_30Rnd_556x45_Mk262",5];
(vestContainer rifleman_1) addmagazinecargoGlobal ["smokeshell",5];
(vestContainer rifleman_1) addmagazinecargoGlobal ["handgrenade",3];
rifleman_1 forceAddUniform "U_B_GhillieSuit";
clearItemCargoGlobal (uniformContainer rifleman_1);
clearMagazineCargoGlobal (uniformContainer rifleman_1);
clearWeaponCargoGlobal (uniformContainer rifleman_1);
(uniformContainer rifleman_1) addmagazinecargoGlobal ["11Rnd_45ACP_Mag",1];
(uniformContainer rifleman_1) addmagazinecargoGlobal ["RH_30Rnd_556x45_Mk262",1];
rifleman_1 addWeapon "ItemRadio";
rifleman_1 selectWeapon (primaryWeapon rifleman_1);
	};
};

if (!isNil "rifleman_2") then {
	if (player == rifleman_2) exitwith {
removeallweapons rifleman_2;
removeallassigneditems rifleman_2;
removeBackpack rifleman_2;
removeVest rifleman_2;
removeHeadgear rifleman_2;
removeUniform rifleman_2;
removeGoggles rifleman_2;

rifleman_2 addWeapon "ItemMap";
rifleman_2 addWeapon "ItemWatch";
rifleman_2 addWeapon "ItemCompass";
rifleman_2 addWeapon "ItemGPS";
rifleman_2  addWeapon "G_Tactical_Clear";
rifleman_2 addWeapon "NVGoggles";
rifleman_2 addWeapon "H_HelmetB_desert";
rifleman_2 addBackpack "B_Carryall_khk";
(backpackContainer rifleman_2) addmagazinecargoGlobal ["RH_30Rnd_556x45_Mk262",1];
rifleman_2 addWeapon "RH_m4a1_ris_tg";
removeBackpack rifleman_2;
rifleman_2 addPrimaryWeaponItem "RH_saker_tg";
rifleman_2 addPrimaryWeaponItem "optic_HAMR";
rifleman_2 addPrimaryWeaponItem "RH_peq15";
rifleman_2 addBackpack "B_Carryall_khk";
(backpackContainer rifleman_2) addmagazinecargoGlobal ["11Rnd_45ACP_Mag",1];
rifleman_2 addWeapon "hgun_Pistol_heavy_01_MRD_F";
rifleman_2 addHandgunItem "muzzle_snds_acp";
removeBackpack rifleman_2;
rifleman_2 addBackpack "B_Carryall_khk";
clearItemCargoGlobal (backpackContainer rifleman_2);
clearMagazineCargoGlobal (backpackContainer rifleman_2);
clearWeaponCargoGlobal (backpackContainer rifleman_2);
(backpackContainer rifleman_2) addmagazinecargoGlobal ["RH_30Rnd_556x45_Mk262",1];
(backpackContainer rifleman_2) addmagazinecargoGlobal ["APERSBoundingMine_Range_Mag",3];
(backpackContainer rifleman_2) additemcargoGlobal ["cse_bandage_basic",5];
(backpackContainer rifleman_2) additemcargoGlobal ["cse_packing_bandage",3];
(backpackContainer rifleman_2) additemcargoGlobal ["cse_morphine",2];
(backpackContainer rifleman_2) additemcargoGlobal ["cse_quikclot",4];
rifleman_2 addVest "V_TacVest_brn";
clearItemCargoGlobal (vestContainer rifleman_2);
clearMagazineCargoGlobal (vestContainer rifleman_2);
clearWeaponCargoGlobal (vestContainer rifleman_2);
(vestContainer rifleman_2) addmagazinecargoGlobal ["RH_30Rnd_556x45_Mk262",5];
(vestContainer rifleman_2) addmagazinecargoGlobal ["smokeshell",5];
(vestContainer rifleman_2) addmagazinecargoGlobal ["handgrenade",3];
rifleman_2 forceAddUniform "U_B_GhillieSuit";
clearItemCargoGlobal (uniformContainer rifleman_2);
clearMagazineCargoGlobal (uniformContainer rifleman_2);
clearWeaponCargoGlobal (uniformContainer rifleman_2);
(uniformContainer rifleman_2) addmagazinecargoGlobal ["11Rnd_45ACP_Mag",1];
(uniformContainer rifleman_2) addmagazinecargoGlobal ["RH_30Rnd_556x45_Mk262",1];
rifleman_2 addWeapon "ItemRadio";
rifleman_2 selectWeapon (primaryWeapon rifleman_2);
	};
};

if (!isNil "rifleman_3") then {
	if (player == rifleman_3) exitwith {
removeallweapons rifleman_3;
removeallassigneditems rifleman_3;
removeBackpack rifleman_3;
removeVest rifleman_3;
removeHeadgear rifleman_3;
removeUniform rifleman_3;
removeGoggles rifleman_3;

rifleman_3 addWeapon "ItemMap";
rifleman_3 addWeapon "ItemWatch";
rifleman_3 addWeapon "ItemCompass";
rifleman_3 addWeapon "ItemGPS";
rifleman_3  addWeapon "G_Tactical_Clear";
rifleman_3 addWeapon "NVGoggles";
rifleman_3 addWeapon "H_HelmetB_desert";
rifleman_3 addBackpack "B_Carryall_khk";
(backpackContainer rifleman_3) addmagazinecargoGlobal ["RH_30Rnd_556x45_Mk262",1];
rifleman_3 addWeapon "RH_m4a1_ris_tg";
removeBackpack rifleman_3;
rifleman_3 addPrimaryWeaponItem "RH_saker_tg";
rifleman_3 addPrimaryWeaponItem "optic_HAMR";
rifleman_3 addPrimaryWeaponItem "RH_peq15";
rifleman_3 addBackpack "B_Carryall_khk";
(backpackContainer rifleman_3) addmagazinecargoGlobal ["11Rnd_45ACP_Mag",1];
rifleman_3 addWeapon "hgun_Pistol_heavy_01_MRD_F";
rifleman_3 addHandgunItem "muzzle_snds_acp";
removeBackpack rifleman_3;
rifleman_3 addBackpack "B_Carryall_khk";
clearItemCargoGlobal (backpackContainer rifleman_3);
clearMagazineCargoGlobal (backpackContainer rifleman_3);
clearWeaponCargoGlobal (backpackContainer rifleman_3);
(backpackContainer rifleman_3) addmagazinecargoGlobal ["RH_30Rnd_556x45_Mk262",1];
(backpackContainer rifleman_3) addmagazinecargoGlobal ["APERSBoundingMine_Range_Mag",3];
(backpackContainer rifleman_3) additemcargoGlobal ["cse_bandage_basic",5];
(backpackContainer rifleman_3) additemcargoGlobal ["cse_packing_bandage",3];
(backpackContainer rifleman_3) additemcargoGlobal ["cse_morphine",2];
(backpackContainer rifleman_3) additemcargoGlobal ["cse_quikclot",4];
rifleman_3 addVest "V_TacVest_brn";
clearItemCargoGlobal (vestContainer rifleman_3);
clearMagazineCargoGlobal (vestContainer rifleman_3);
clearWeaponCargoGlobal (vestContainer rifleman_3);
(vestContainer rifleman_3) addmagazinecargoGlobal ["RH_30Rnd_556x45_Mk262",5];
(vestContainer rifleman_3) addmagazinecargoGlobal ["smokeshell",5];
(vestContainer rifleman_3) addmagazinecargoGlobal ["handgrenade",3];
rifleman_3 forceAddUniform "U_B_GhillieSuit";
clearItemCargoGlobal (uniformContainer rifleman_3);
clearMagazineCargoGlobal (uniformContainer rifleman_3);
clearWeaponCargoGlobal (uniformContainer rifleman_3);
(uniformContainer rifleman_3) addmagazinecargoGlobal ["11Rnd_45ACP_Mag",1];
(uniformContainer rifleman_3) addmagazinecargoGlobal ["RH_30Rnd_556x45_Mk262",1];
rifleman_3 addWeapon "ItemRadio";
rifleman_3 selectWeapon (primaryWeapon rifleman_3);
	};
};

if (!isNil "rifleman_4") then {
	if (player == rifleman_4) exitwith {
removeallweapons rifleman_4;
removeallassigneditems rifleman_4;
removeBackpack rifleman_4;
removeVest rifleman_4;
removeHeadgear rifleman_4;
removeUniform rifleman_4;
removeGoggles rifleman_4;

rifleman_4 addWeapon "ItemMap";
rifleman_4 addWeapon "ItemWatch";
rifleman_4 addWeapon "ItemCompass";
rifleman_4 addWeapon "ItemGPS";
rifleman_4  addWeapon "G_Tactical_Clear";
rifleman_4 addWeapon "NVGoggles";
rifleman_4 addWeapon "H_HelmetB_desert";
rifleman_4 addBackpack "B_Carryall_khk";
(backpackContainer rifleman_4) addmagazinecargoGlobal ["RH_30Rnd_556x45_Mk262",1];
rifleman_4 addWeapon "RH_m4a1_ris_tg";
removeBackpack rifleman_4;
rifleman_4 addPrimaryWeaponItem "RH_saker_tg";
rifleman_4 addPrimaryWeaponItem "optic_HAMR";
rifleman_4 addPrimaryWeaponItem "RH_peq15";
rifleman_4 addBackpack "B_Carryall_khk";
(backpackContainer rifleman_4) addmagazinecargoGlobal ["11Rnd_45ACP_Mag",1];
rifleman_4 addWeapon "hgun_Pistol_heavy_01_MRD_F";
rifleman_4 addHandgunItem "muzzle_snds_acp";
removeBackpack rifleman_4;
rifleman_4 addBackpack "B_Carryall_khk";
clearItemCargoGlobal (backpackContainer rifleman_4);
clearMagazineCargoGlobal (backpackContainer rifleman_4);
clearWeaponCargoGlobal (backpackContainer rifleman_4);
(backpackContainer rifleman_4) addmagazinecargoGlobal ["RH_30Rnd_556x45_Mk262",1];
(backpackContainer rifleman_4) addmagazinecargoGlobal ["APERSBoundingMine_Range_Mag",3];
(backpackContainer rifleman_4) additemcargoGlobal ["cse_bandage_basic",5];
(backpackContainer rifleman_4) additemcargoGlobal ["cse_packing_bandage",3];
(backpackContainer rifleman_4) additemcargoGlobal ["cse_morphine",2];
(backpackContainer rifleman_4) additemcargoGlobal ["cse_quikclot",4];
rifleman_4 addVest "V_TacVest_brn";
clearItemCargoGlobal (vestContainer rifleman_4);
clearMagazineCargoGlobal (vestContainer rifleman_4);
clearWeaponCargoGlobal (vestContainer rifleman_4);
(vestContainer rifleman_4) addmagazinecargoGlobal ["RH_30Rnd_556x45_Mk262",5];
(vestContainer rifleman_4) addmagazinecargoGlobal ["smokeshell",5];
(vestContainer rifleman_4) addmagazinecargoGlobal ["handgrenade",3];
rifleman_4 forceAddUniform "U_B_GhillieSuit";
clearItemCargoGlobal (uniformContainer rifleman_4);
clearMagazineCargoGlobal (uniformContainer rifleman_4);
clearWeaponCargoGlobal (uniformContainer rifleman_4);
(uniformContainer rifleman_4) addmagazinecargoGlobal ["11Rnd_45ACP_Mag",1];
(uniformContainer rifleman_4) addmagazinecargoGlobal ["RH_30Rnd_556x45_Mk262",1];
rifleman_4 addWeapon "ItemRadio";
rifleman_4 selectWeapon (primaryWeapon rifleman_4);
	};
};


if (!isNil "rifleman_AT") then {
	if (player == rifleman_AT) exitwith {
removeallweapons rifleman_AT;
removeallassigneditems rifleman_AT;
removeBackpack rifleman_AT;
removeVest rifleman_AT;
removeHeadgear rifleman_AT;
removeUniform rifleman_AT;
removeGoggles rifleman_AT;
rifleman_AT addWeapon "ItemMap";
rifleman_AT addWeapon "ItemWatch";
rifleman_AT addWeapon "ItemCompass";
rifleman_AT addWeapon "ItemGPS";
rifleman_AT  addWeapon "G_Tactical_Clear";
rifleman_AT addWeapon "NVGoggles";
rifleman_AT addWeapon "H_HelmetB_desert";
rifleman_AT addWeapon "launch_NLAW_F";
rifleman_AT addBackpack "B_Carryall_khk";
(backpackContainer rifleman_AT) addmagazinecargoGlobal ["RH_30Rnd_556x45_Mk262",1];
rifleman_AT addWeapon "RH_m4a1_ris_tg";
removeBackpack rifleman_AT;
rifleman_AT addPrimaryWeaponItem "RH_saker_tg";
rifleman_AT addPrimaryWeaponItem "optic_HAMR";
rifleman_AT addPrimaryWeaponItem "RH_peq15";
rifleman_AT addBackpack "B_Carryall_khk";
(backpackContainer rifleman_AT) addmagazinecargoGlobal ["11Rnd_45ACP_Mag",1];
rifleman_AT addWeapon "hgun_Pistol_heavy_01_MRD_F";
rifleman_AT addHandgunItem "muzzle_snds_acp";
removeBackpack rifleman_AT;
rifleman_AT addBackpack "B_Carryall_khk";
clearItemCargoGlobal (backpackContainer rifleman_AT);
clearMagazineCargoGlobal (backpackContainer rifleman_AT);
clearWeaponCargoGlobal (backpackContainer rifleman_AT);
(backpackContainer rifleman_AT) addmagazinecargoGlobal ["RH_30Rnd_556x45_Mk262",1];
(backpackContainer rifleman_AT) additemcargoGlobal ["cse_bandage_basic",5];
(backpackContainer rifleman_AT) additemcargoGlobal ["cse_packing_bandage",3];
(backpackContainer rifleman_AT) additemcargoGlobal ["cse_morphine",2];
(backpackContainer rifleman_AT) additemcargoGlobal ["cse_quikclot",4];
(backpackContainer rifleman_AT) addMagazinecargoGlobal ["NLAW_F",3];
rifleman_AT addVest "V_TacVest_brn";
clearItemCargoGlobal (vestContainer rifleman_AT);
clearMagazineCargoGlobal (vestContainer rifleman_AT);
clearWeaponCargoGlobal (vestContainer rifleman_AT);
(vestContainer rifleman_AT) addmagazinecargoGlobal ["RH_30Rnd_556x45_Mk262",5];
(vestContainer rifleman_AT) addmagazinecargoGlobal ["smokeshell",5];
(vestContainer rifleman_AT) addmagazinecargoGlobal ["handgrenade",3];
rifleman_AT forceAddUniform "U_B_GhillieSuit";
clearItemCargoGlobal (uniformContainer rifleman_AT);
clearMagazineCargoGlobal (uniformContainer rifleman_AT);
clearWeaponCargoGlobal (uniformContainer rifleman_AT);
(uniformContainer rifleman_AT) addmagazinecargoGlobal ["11Rnd_45ACP_Mag",1];
(uniformContainer rifleman_AT) addmagazinecargoGlobal ["RH_30Rnd_556x45_Mk262",1];
rifleman_AT addWeapon "ItemRadio";
rifleman_AT selectWeapon (primaryWeapon rifleman_AT);

	};
};

if (!isNil "ammobearer") then {
	if (player == ammobearer) exitwith {
removeallweapons ammobearer;
removeallassigneditems ammobearer;
removeBackpack ammobearer;
removeVest ammobearer;
removeHeadgear ammobearer;
removeUniform ammobearer;
removeGoggles ammobearer;
ammobearer addWeapon "ItemMap";
ammobearer addWeapon "ItemWatch";
ammobearer addWeapon "ItemCompass";
ammobearer addWeapon "ItemGPS";
ammobearer  addWeapon "G_Tactical_Clear";
ammobearer addWeapon "NVGoggles";
ammobearer addWeapon "H_HelmetB_desert";
ammobearer addBackpack "B_Carryall_khk";
(backpackContainer ammobearer) addmagazinecargoGlobal ["RH_30Rnd_556x45_Mk262",1];
ammobearer addWeapon "RH_m4a1_ris_tg";
removeBackpack ammobearer;
ammobearer addPrimaryWeaponItem "RH_saker_tg";
ammobearer addPrimaryWeaponItem "optic_HAMR";
ammobearer addPrimaryWeaponItem "RH_peq15";
ammobearer addBackpack "B_Carryall_khk";
(backpackContainer ammobearer) addmagazinecargoGlobal ["11Rnd_45ACP_Mag",1];
ammobearer addWeapon "hgun_Pistol_heavy_01_MRD_F";
ammobearer addHandgunItem "muzzle_snds_acp";
removeBackpack ammobearer;
ammobearer addBackpack "B_Carryall_khk";
clearItemCargoGlobal (backpackContainer ammobearer);
clearMagazineCargoGlobal (backpackContainer ammobearer);
clearWeaponCargoGlobal (backpackContainer ammobearer);
(backpackContainer ammobearer) addmagazinecargoGlobal ["RH_30Rnd_556x45_Mk262",5];
(backpackContainer ammobearer) additemcargoGlobal ["cse_bandage_basic",5];
(backpackContainer ammobearer) additemcargoGlobal ["cse_packing_bandage",3];
(backpackContainer ammobearer) additemcargoGlobal ["cse_morphine",2];
(backpackContainer ammobearer) additemcargoGlobal ["cse_quikclot",4];
(backpackContainer ammobearer) addMagazinecargoGlobal ["NLAW_F",2];
(backpackContainer ammobearer) addmagazinecargoGlobal ["7Rnd_408_Mag",3];
ammobearer addVest "V_TacVest_brn";
clearItemCargoGlobal (vestContainer ammobearer);
clearMagazineCargoGlobal (vestContainer ammobearer);
clearWeaponCargoGlobal (vestContainer ammobearer);
(vestContainer ammobearer) addmagazinecargoGlobal ["RH_30Rnd_556x45_Mk262",5];
(vestContainer ammobearer) addmagazinecargoGlobal ["smokeshell",5];
(vestContainer ammobearer) addmagazinecargoGlobal ["handgrenade",3];
ammobearer forceAddUniform "U_B_GhillieSuit";
clearItemCargoGlobal (uniformContainer ammobearer);
clearMagazineCargoGlobal (uniformContainer ammobearer);
clearWeaponCargoGlobal (uniformContainer ammobearer);
(uniformContainer ammobearer) addmagazinecargoGlobal ["11Rnd_45ACP_Mag",1];
(uniformContainer ammobearer) addmagazinecargoGlobal ["RH_30Rnd_556x45_Mk262",1];
ammobearer addWeapon "ItemRadio";
ammobearer selectWeapon (primaryWeapon ammobearer);
	};
};